import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import logo from '../public/logo.png';
import { Nav } from '../components/Nav/Nav';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX Stats</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* <main> */}
      <div className={styles.logo}>
        <Image src={logo} />
        <Nav />
      </div>
      {/* </main> */}
    </div>
  );
};

export default Home;
